# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "dcase_task5"
  name: ${exp_name}-${now:%m-%d-%H:%M-%Y}
  save_dir: "."
  offline: False 
  id: null 
  log_model: True
  prefix: ""
  job_type: "train"
  group: "" 
  tags: ["dynamic","pcen","train_seglen"]
 