# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "debug_dcase_task5"
  name: "dynamic"
  save_dir: "."
  offline: False 
  id: null 
  log_model: True
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
